"""empty message

Revision ID: c314d5ef5022
Revises: 
Create Date: 2021-04-03 23:33:42.607233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c314d5ef5022'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry', sa.String(length=120), nullable=True),
    sa.Column('project', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_entry'), 'entry', ['entry'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_entry'), table_name='entry')
    op.drop_table('entry')
    # ### end Alembic commands ###
